uploads = []
outputs = []

[[generated]]
id = "R9y9fWxEVT5H-OTWJI38G"
uri = "file://artifacts/aetherforge/src/assets/commanders/aldric.png"
type = "image"
title = "Sir Aldric warden portrait"

[[generated]]
id = "n761NqiEQNIxf2N8lBNCk"
uri = "file://artifacts/aetherforge/src/assets/commanders/myrra.png"
type = "image"
title = "Myrra starseer portrait"

[[generated]]
id = "lXQvdJYfYX3MRQ-c6zz02"
uri = "file://artifacts/aetherforge/src/assets/commanders/rakkan.png"
type = "image"
title = "Rakkan pride-father portrait"

[[generated]]
id = "MP5_JQZJEnxVE0A41Iswn"
uri = "file://artifacts/aetherforge/src/assets/commanders/korven.png"
type = "image"
title = "Korven ashheart portrait"

[[generated]]
id = "XfH8I3N59HAvLJu9dNKXo"
uri = "file://artifacts/aetherforge/src/assets/commanders/silkweaver.png"
type = "image"
title = "Mother Silkweaver portrait"

[[generated]]
id = "q2WTuzpvAxBqs-kRHg-xW"
uri = "file://artifacts/aetherforge/src/assets/commanders/hollowqueen.png"
type = "image"
title = "Hollow Queen portrait"

[[generated]]
id = "LpUM9TYTIrNPlhb5oqyPw"
uri = "file://artifacts/aetherforge/src/assets/commanders/brunhild.png"
type = "image"
title = "Brunhild unbroken portrait"

[[generated]]
id = "vp--6MHBimRXfzYToHDx4"
uri = "file://artifacts/aetherforge/src/assets/nodes/battle.png"
type = "image"
title = "Battle node icon v2"

[[generated]]
id = "SmjfwxiJOlKTeClwTF-nZ"
uri = "file://artifacts/aetherforge/src/assets/nodes/elite.png"
type = "image"
title = "Elite node icon v2"

[[generated]]
id = "auPlwh_9UJAjpUTHyjoJz"
uri = "file://artifacts/aetherforge/src/assets/nodes/shop.png"
type = "image"
title = "Shop node icon v2"

[[generated]]
id = "tbhO95fQXwsOD5ou32GaT"
uri = "file://artifacts/aetherforge/src/assets/nodes/town.png"
type = "image"
title = "Town node icon v2"

[[generated]]
id = "hd_db1nr_GASsjJGDmWc1"
uri = "file://artifacts/aetherforge/src/assets/nodes/forge.png"
type = "image"
title = "Forge node icon v2"

[[generated]]
id = "Zdg9u7M72VX28oLAM4u1O"
uri = "file://artifacts/aetherforge/src/assets/nodes/rest.png"
type = "image"
title = "Rest node icon v2"

[[generated]]
id = "3tYWzmCO91iX3xJQEdut7"
uri = "file://artifacts/aetherforge/src/assets/nodes/event.png"
type = "image"
title = "Event node icon v2"

[[generated]]
id = "3gyVA6jg_r3Da_mEgR0O4"
uri = "file://artifacts/aetherforge/src/assets/nodes/boss.png"
type = "image"
title = "Boss node icon v2"
